trigger: none
pool:
  vmImage: ubuntu-latest
variables:
  test: 'dd'

stages:
  - stage: A
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: install terraform
            inputs:
              terraformVersion: 'latest'
    
      
        