trigger: none

pool:
  vmImage: ubuntu-latest
variables:
- group: terraform_dev 

stages:
  - stage: 'TerraformStageDev'
    jobs: 
      - job: 'TerraForminit'
        continueOnError: false
        steps:
          - script: echo $(bkstrgkey)
            displayName: Print variables
            
          - task: TerraformInstaller@1
            displayName: install terraform
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: terrafor init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Visual Studio Professional with MSDN(c4e74058-4994-4f0f-865e-de488376ac75)'
              backendAzureRmResourceGroupName: $(bkstrgrg)
              backendAzureRmStorageAccountName: $(bkstrg)
              backendAzureRmContainerName: $(bkcontainer)
              backendAzureRmKey: $(bkstrgkey)
                   

          - task: TerraformTaskV4@4
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Visual Studio Professional with MSDN(c4e74058-4994-4f0f-865e-de488376ac75)'
        
          - task: TerraformTaskV4@4
            displayName: Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Visual Studio Professional with MSDN(c4e74058-4994-4f0f-865e-de488376ac75)'
    
  - stage: 'TerraformStageProd'
    condition: succeeded()
    dependsOn: TerraformStageDev
    displayName: 'Terraform Stage Prod'
    jobs:
      - job: 
        variables:
          bkstrgrg: 'test'
          bkstrg: 'xy123498'
          bkcontainer : 'terraform'
          bkstrgkey : 'terraform.tfstate.prod'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Visual Studio Professional with MSDN(c4e74058-4994-4f0f-865e-de488376ac75)'
              backendAzureRmResourceGroupName: $(bkstrgrg)
              backendAzureRmStorageAccountName: $(bkstrg)
              backendAzureRmContainerName: $(bkcontainer)
              backendAzureRmKey: $(bkstrgkey)
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Visual Studio Professional with MSDN(c4e74058-4994-4f0f-865e-de488376ac75)'
          


    
        